name: CI/CD

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0 # full history + tags, needed by MinVer to compute the version

      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build

      - name: Pack
        run: dotnet pack WiseAuth/WiseAuth.csproj --configuration Release --no-build --output ./artifacts

      - name: Upload NuGet package
        uses: actions/upload-artifact@v7
        with:
          name: nuget-package
          path: ./artifacts/*.nupkg

  publish:
    needs: build-test
    environment: production
    permissions:
      id-token: write  # enable GitHub OIDC token issuance for this job
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download NuGet package
        uses: actions/download-artifact@v8
        with:
          name: nuget-package
          path: ./artifacts

      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'

      # Get a short-lived NuGet API key
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      # Push the package      
      - name: Push to NuGet.org
        run: dotnet nuget push ./artifacts/WiseAuth.*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate